### ISSUE TITLE
Result issue

### ISSUE THREAD

**Issue by zlxx629** [rabiul-ai/Arrhythmia_Classification#2]
![image](https://github.com/user-attachments/assets/4b3d915e-cffa-4d01-91da-cfcded9660b2)
![image](https://github.com/user-attachments/assets/e500b5f7-1172-4c4a-bbc5-17fc59c29dda)

May I ask why the accuracy is only 0.2 and the loss does not decrease when I run according to the steps, but the accuracy can reach 0.8 when I do not use SMOTE to balance the data? How can I solve this problem

**Comment by rabiul-ai** [comment]
First, of course you are making some mistakes; otherwise, the code is 100% correct for giving you the accuracy of more than 90%. I saw you only run for 5 epochs; it should be high. Second, focus on how you are utilizing data after using SMOTE. Take your time; do step by step. It will must give you good results, subject to you are doing it correctly as given.

**Comment by rabiul-ai** [comment]
> ![image](https://private-user-images.githubusercontent.com/149983182/370175739-4b3d915e-cffa-4d01-91da-cfcded9660b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTE5MDEsIm5iZiI6MTczMzgxMTYwMSwicGF0aCI6Ii8xNDk5ODMxODIvMzcwMTc1NzM5LTRiM2Q5MTVlLWNmZmEtNGQwMS05MWRhLWNmY2RlZDk2NjBiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwNjIwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTY1MzQ3NGJjNzZjZmI2OWY5OTczMjJlNzY5ZDI4NWMxYmQxZGRlODI0ZDMwN2I2NDkyYzI2ZWU3YmJmYjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rIrgqUMiX5dx-0tPpa0wYjzFUKjicU2YsdH0nNxogWo) ![image](https://private-user-images.githubusercontent.com/149983182/370176466-e500b5f7-1172-4c4a-bbc5-17fc59c29dda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTE5MDEsIm5iZiI6MTczMzgxMTYwMSwicGF0aCI6Ii8xNDk5ODMxODIvMzcwMTc2NDY2LWU1MDBiNWY3LTExNzItNGM0YS1iYmM1LTE3ZmM1OWMyOWRkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwNjIwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGQ1MjVhZTI1M2ZkNjAzNzY0MTM2OGZlMWQ0MWY3OTZhM2M3NzE1ZmM1OWM0NGY1NTg3YzY1ZDA1OWVlOGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2Wq1DV8ouGnNlFonDwsVkWdTDI4NyRHCbLohLMwunFw)
> 
> May I ask why the accuracy is only 0.2 and the loss does not decrease when I run according to the steps, but the accuracy can reach 0.8 when I do not use SMOTE to balance the data? How can I solve this problem

First, of course you are making some mistakes; otherwise, the code is 100% correct for giving you the accuracy of more than 90%. I saw you only run for 5 epochs; it should be high. Second, focus on how you are utilizing data after using SMOTE. Take your time; do step by step. It will must give you good results, subject to you are doing it correctly as given.
